---
title:               Siddharth Kothari
tagline:             Discoveries, failings, things worth remembering
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Siddharth Kothari
twitter:             sids_aquarius
github:              sids-aquarius
email:               sids.aquarius@gmail.com
portfolio:           projects.sidsaquarius.in
google_analytics_id: UA-26965840-1
